export const bibtex = `---
---


@article{reichstein2025ews,
  abbr = {Nat. Commun.},
  title={Early warning of complex climate risk with integrated artificial intelligence},
  author={Reichstein*, Markus and Benson*, Vitus and Blunk, Jan and Camps-Valls, Gustau and Creutzig, Felix and Fearnley, Carina J and Han, Boran and Kornhuber, Kai and Rahaman, Nasim and Sch{\"o}lkopf, Bernhard and Tárraga, José María and Frank, Dorothea and Martini, Giulia and Vinuesa, Ricardo and Dall, Karen and Denzler, Joachim and Nganga, Naomi and Maddix Robinson, Danielle and Weldemariam, Kommy},
  journal={Nature Communications},
  volume={16},
  number={1},
  pages={2564},
  year={2025},
  month={March},
  publisher={Nature Publishing Group UK London},
  pdf={https://www.nature.com/articles/s41467-025-57640-w},
  preview={reichstein_ncomms_2025.png},
  selected={true},
  bibtex_show={true},
}

@article{camps2025artificial,
  abbr = {Nat. Commun.},
  title={Artificial intelligence for modeling and understanding extreme weather and climate events},
  author={Camps-Valls, Gustau and Fern{\'a}ndez-Torres, Miguel-{\'A}ngel and Cohrs, Kai-Hendrik and H{\"o}hl, Adrian and Castelletti, Andrea and Pacal, Aytac and Robin, Claire and Martinuzzi, Francesco and Papoutsis, Ioannis and Prapas, Ioannis and others},
  journal={Nature Communications},
  volume={16},
  number={1},
  pages={1919},
  year={2025},
  month={February},
  publisher={Nature Publishing Group UK London},
  pdf={https://www.nature.com/articles/s41467-025-56573-8},
  preview={camps_ncomms_2025.png},
  selected={true},
  bibtex_show={true},
}
@article{ji2025deepextremecubes,
  abbr = {Sci. Data},
  title={DeepExtremeCubes: Earth system spatio-temporal data for assessing compound heatwave and drought impacts},
  author={Ji, Chaonan and Fincke, Tonio and Benson, Vitus and Camps-Valls, Gustau and Fern{\'a}ndez-Torres, Miguel-{\'A}ngel and Gans, Fabian and Kraemer, Guido and Martinuzzi, Francesco and Montero, David and Mora, Karin and Pellicer-Valero, Oscar J. and Robin, Claire and Söchting, Maximilian and Weynants, Mélanie and Mahecha, Miguel D.},
  journal={Scientific Data},
  volume={12},
  number={1},
  pages={149},
  year={2025},
  month={January},
  publisher={Nature Publishing Group UK London},
  pdf={https://doi.org/10.1038/s41597-025-04447-5},
  bibtex_show={true},
  selected={false},
  preview = {ji_scidata_2025.png},
  code={https://github.com/DeepExtremes/minicube-generation},
}

@article{benson2024multimodal,
      abbr = {CVPR},
      title={Multi-modal Learning for Geospatial Vegetation Forecasting}, 
      author={Benson, Vitus and Robin, Claire and Requena-Mesa, Christian and Alonso, Lazaro and Carvalhais, Nuno and Cort{\'e}s, Jos{\'e} and Gao, Zhihan and Linscheid, Nora and Weynants, M{\'e}lanie and Reichstein, Markus},
      year={2024},
      month = {June},
      pages = {27788-27799},
      journal = {Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)},
      pdf={https://openaccess.thecvf.com/content/CVPR2024/html/Benson_Multi-modal_Learning_for_Geospatial_Vegetation_Forecasting_CVPR_2024_paper.html},
      bibtex_show={true},
      selected={true},
      preview = {benson_cvpr_2024.gif},
      code={https://github.com/vitusbenson/greenearthnet},
}


@article{requena-mesa.etal_2021,
  abbr = {EarthVision},
  title = {{{EarthNet2021}}: {{A Large-Scale Dataset}} and {{Challenge}} for {{Earth Surface Forecasting}} as a {{Guided Video Prediction Task}}.},
  author = {Requena-Mesa*, Christian and Benson*, Vitus and Reichstein, Markus and Runge, Jakob and Denzler, Joachim},
  year = {2021},
  month = {June},
  pages = {1132--1142},
  pdf = {https://openaccess.thecvf.com/content/CVPR2021W/EarthVision/html/Requena-Mesa_EarthNet2021_A_Large-Scale_Dataset_and_Challenge_for_Earth_Surface_Forecasting_CVPRW_2021_paper.html},
  journal = {Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR) Workshops},
  bibtex_show={true},
  selected={false},
  preview = {requenamesa_earthvision_2021.gif},
}

@article{robin.etal_2022,
  abbr = {TCCML},
  title = {Learning to Forecast Vegetation Greenness at Fine Resolution over {{Africa}} with {{ConvLSTMs}}},
  author = {Robin, Claire and Requena-Mesa, Christian and Benson, Vitus and Alonso, Lazaro and Poehls, Jeran and Carvalhais, Nuno and Reichstein, Markus},
  year = {2022},
  month = {December},
  pdf = {http://arxiv.org/abs/2210.13648},
  journal = {NeurIPS Workshop Tackling {{Climate Change}} with {{Machine Learning}}},
  bibtex_show={true},
  selected={false},
  preview = {robin_tccml_2022.png},
}`;
